name: Release
on:
  # manual trigger
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  deploy:
    name: release
    runs-on:
      group: npm-deploy
    environment:
      name: release
    permissions:
      id-token: write
      contents: read
    
    timeout-minutes: 20
    steps:
      - name: Load secret
        uses: 1password/load-secrets-action@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3.0.0
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # You may need to change this to your vault name and secret name
          # Refer to it by calling env.NPM_TOKEN
          # This token is also limited by IP to ONLY work on the runner
          NPM_TOKEN: op://npm-deploy/npm-runner-token/secret
      
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: yarn
          node-version: "20.17.0"
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache --non-interactive

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --ci

      - name: Decide npm tag
        id: tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" == *-* ]]; then
            PREID=$(echo "$VERSION" | cut -d'-' -f2 | cut -d'.' -f1)
            echo "tag=$PREID" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken "${NODE_AUTH_TOKEN}"
          npm publish --provenance --access public --tag "${{ steps.tag.outputs.tag }}"
